# TODO:
# - cgi version
Summary:	innpeer-stats - Yet Another statistic tool for INN
Name:		innpeer-stats
Version:	0.03
Release:	1
License:	GPL v2+
Group:		Networking/Daemons
Source0:	http://www.sofaraway.org/projects/innpeer-stats/%{name}-%{version}.tar.gz
# Source0-md5:	8dcba6d3f1df906176f408d360cab9d5
Patch0:		%{name}-conf.patch
URL:		http://www.sofaraway.org/projects/innpeer-stats/
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%define		_sysconfdir	/etc/%{name}

%description
innpeer-stats is an application producing a lot of fancy graphics 
concerning usenet peers. Both incoming and outgoing reports are available.
Data are extracted from the current syslog file generated by INN (in
this version, only innd and innfeed logs are processed). This is very
useful to tune your server or to debug strange problems.

%prep
%setup -q -n %{name}
%patch -P0 -p1

%build
%{__make} \
	CC="%{__cc}" \
	COPTS="%{rpmcflags}"

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT{%{_sysconfdir},%{_bindir}}

install %{name} $RPM_BUILD_ROOT%{_bindir}
install innpeer-groups.conf $RPM_BUILD_ROOT%{_sysconfdir}

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
%doc README
%attr(750,root,news) %dir %{_sysconfdir}
%attr(640,root,news) %config(noreplace) %verify(not md5 mtime size) %{_sysconfdir}/*
%attr(755,root,root) %{_bindir}/%{name}
